<a href="https://colab.research.google.com/github/suramyatuladhar22/Math/blob/main/Workshop6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####Part 1: Create and Understand Ndarray:
Ndarray object represents N-dimensional array. Ndarray has different properties/attributes,
which are useful information about the ndarray object.

#####Problem 1:
                                          
Create a 2D ndarray of type Integer, e.g.,

    [ 1 2 3 ]
    | 4 5 6 |
    [ 7 8 9 ]                                   
and see its properties                                                       
                                          

In [2]:
import numpy as np
arr = np.array([ [1,2, 3], [4, 5,6], [7,8,9]], dtype=float)
print("Array =")
print(arr)
print("Data Type of the Array =",arr.dtype)
print("Number of dimensions of the Array =",arr.ndim)
print("Shape of the Array =",arr.shape)
print("Size of the Array =",arr.size)
print("Number of bytes used by each element of the Array =",arr.itemsize)
print("Total bytes used by the Array =",arr.nbytes)
print( "Memory Lavout information =",arr.flags)


Array =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Array = float64
Number of dimensions of the Array = 2
Shape of the Array = (3, 3)
Size of the Array = 9
Number of bytes used by each element of the Array = 8
Total bytes used by the Array = 72
Memory Lavout information =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



####Problem 2:
Create a 2D ndarray (matrix) of shape (4,5) with all elements equal to 3.0 and print
the matrix.

In [3]:
import numpy as np
arr2 = 3 * np.ones( (4,5), dtype=float)
print("Array =")
print(arr2)
print("Shape =", arr2.shape)
print ("DataType = ", arr2.dtype)

Array =
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape = (4, 5)
DataType =  float64


####Problem 3:
What is the other way to create the same matrix as above?

Hint: See the documentation of function numpy.full() at: numpy.full — NumPy v1.26 Manual

In [4]:
import numpy as np

# Create a 4x5 matrix filled with 3.0
arr2 = np.full((4,5), 3.0, dtype=float)

print("Array =")
print(arr2)
print("Shape =", arr2.shape)
print("DataType =", arr2.dtype)


Array =
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape = (4, 5)
DataType = float64


####Problem 4:
Construct a matrix [aij] of shape (3,3) whose elements are given by aij = 1/2*|i - 3j|.

In [5]:
import numpy as np
arr4 = np. fromfunction(lambda i, j: np.abs(i+1-3*(j+1))/2, (3, 3), dtype=int)
print("Array = ")
print(arr4)
print("Shape = ", arr4.shape)
print("DataType = ", arr4.dtype)

Array = 
[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape =  (3, 3)
DataType =  float64


####Problem 5:
Construct a diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4].

Hint: Use the function numpy.diag() and see the documentation at: numpy.diag - NumPy v1.26
Manual

In [6]:
import numpy as np

# Diagonal elements
diag_elements = [1, 2, 3, 4]

# Construct diagonal matrix
A = np.diag(diag_elements)

print("Diagonal Matrix A:\n", A)
print("Shape =", A.shape)
print("DataType =", A.dtype)


Diagonal Matrix A:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Shape = (4, 4)
DataType = int64


####Problem 6:
Construct a matrix of shape (4,5) with whatever elements, and then slice it to obtaina matrix of shape (3,3) that contains only upper-left portion of the original matrix.

Solution:

    • See how to index the element of a ndarray at:
    https://www.w3schools.com/python/numpy/numpy_array_indexing.asp
    • See how to slice a ndarray at:
    https://www.w3schools.com/python/numpy/numpy_array_slicing.asp

In [7]:
import numpy as np

# Step 1: Construct a 4x5 matrix (example values)
A = np.arange(1, 21).reshape(4, 5)
print("Original 4x5 Matrix A:\n", A)

# Step 2: Slice the upper-left 3x3 portion
B = A[:3, :3]
print("\nSliced 3x3 Upper-Left Matrix B:\n", B)


Original 4x5 Matrix A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sliced 3x3 Upper-Left Matrix B:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


####Part 2: Perform some basic operation on Vectors/Matrices:

####Problem 1:
Create two matrices

    A = [ 1 2 3 ] and B = [ 1 1 1 ] .Add them together. What do you observ. Give the explanation behind it.
        | 4 5 6 |         [ 2 2 2 ]
        [ 7 8 9 ]                            
        

In [11]:
import numpy as np

# Define matrices
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

B = np.array([[1, 1, 1],[2, 2, 2],[0, 0, 0]])

# Add them together
C = A + B

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nA + B =\n", C)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[1 1 1]
 [2 2 2]
 [0 0 0]]

A + B =
 [[2 3 4]
 [6 7 8]
 [7 8 9]]


####Problem 2:
Given a matrix and a vector, write a Python function that performs Matrix-Vector
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-Matrix product.

In [14]:
import numpy as np

def dot_product(vec1, vec2):
    # flatten the input vectors
    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    return np.sum(np.multiply(vec1, vec2))

def matrix_vector_product(mat, vec):
    m, n = mat.shape
    p, q = vec.shape

    assert n == p, "The matrix and vector are not compatible for multiplication!"

    # create a ndarray to store the result
    result = np.zeros((m, q), dtype=float)

    # Loop to perform Matrix-Vector product
    for i in range(m):
        result[i] = dot_product(mat[i, :], vec)

    return result

# Example matrix and vector
mat1 = np.full((3, 3), 3, dtype=int)
vec1 = np.full((3, 1), 2, dtype=int)

print("Matrix =\n", mat1)
print("Vector =\n", vec1)

# Call the custom function
result1 = matrix_vector_product(mat1, vec1)
print("Result (custom function) =\n", result1)

# Check with numpy in-built function for multiplication
result2 = mat1 @ vec1
print("Result (NumPy @ operator) =\n", result2)


Matrix =
 [[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector =
 [[2]
 [2]
 [2]]
Result (custom function) =
 [[18.]
 [18.]
 [18.]]
Result (NumPy @ operator) =
 [[18]
 [18]
 [18]]
